// Code generated by mockery v2.10.1. DO NOT EDIT.

package repository

import mock "github.com/stretchr/testify/mock"

// MockOption is an autogenerated mock type for the Option type
type MockOption struct {
	mock.Mock
}

// Apply provides a mock function with given fields: _a0
func (_m *MockOption) Apply(_a0 Config) {
	_m.Called(_a0)
}
