// Code generated by mockery v2.10.1. DO NOT EDIT.

package repository

import (
	context "context"
	model "txholder/model"

	mock "github.com/stretchr/testify/mock"
)

// MockUserTxHolderRepository is an autogenerated mock type for the UserTxHolderRepository type
type MockUserTxHolderRepository struct {
	mock.Mock
}

// Commit provides a mock function with given fields:
func (_m *MockUserTxHolderRepository) Commit() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateUser provides a mock function with given fields: ctx, user
func (_m *MockUserTxHolderRepository) CreateUser(ctx context.Context, user *model.User) error {
	ret := _m.Called(ctx, user)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.User) error); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteUser provides a mock function with given fields: ctx, userId
func (_m *MockUserTxHolderRepository) DeleteUser(ctx context.Context, userId string) error {
	ret := _m.Called(ctx, userId)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, userId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetUser provides a mock function with given fields: ctx, userId
func (_m *MockUserTxHolderRepository) GetUser(ctx context.Context, userId string) (*model.User, error) {
	ret := _m.Called(ctx, userId)

	var r0 *model.User
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.User); ok {
		r0 = rf(ctx, userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListUsers provides a mock function with given fields: ctx
func (_m *MockUserTxHolderRepository) ListUsers(ctx context.Context) ([]*model.User, error) {
	ret := _m.Called(ctx)

	var r0 []*model.User
	if rf, ok := ret.Get(0).(func(context.Context) []*model.User); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewApplicationTxHolderRepository provides a mock function with given fields:
func (_m *MockUserTxHolderRepository) NewApplicationTxHolderRepository() ApplicationTxHolderRepository {
	ret := _m.Called()

	var r0 ApplicationTxHolderRepository
	if rf, ok := ret.Get(0).(func() ApplicationTxHolderRepository); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ApplicationTxHolderRepository)
		}
	}

	return r0
}

// NewUserTxHolderRepository provides a mock function with given fields:
func (_m *MockUserTxHolderRepository) NewUserTxHolderRepository() UserTxHolderRepository {
	ret := _m.Called()

	var r0 UserTxHolderRepository
	if rf, ok := ret.Get(0).(func() UserTxHolderRepository); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(UserTxHolderRepository)
		}
	}

	return r0
}

// Rollback provides a mock function with given fields:
func (_m *MockUserTxHolderRepository) Rollback() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
