// Code generated by mockery v2.10.1. DO NOT EDIT.

package repository

import mock "github.com/stretchr/testify/mock"

// MockRepositoryCreator is an autogenerated mock type for the RepositoryCreator type
type MockRepositoryCreator struct {
	mock.Mock
}

// NewApplicationRepository provides a mock function with given fields:
func (_m *MockRepositoryCreator) NewApplicationRepository() ApplicationRepository {
	ret := _m.Called()

	var r0 ApplicationRepository
	if rf, ok := ret.Get(0).(func() ApplicationRepository); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ApplicationRepository)
		}
	}

	return r0
}

// NewUserRepository provides a mock function with given fields:
func (_m *MockRepositoryCreator) NewUserRepository() UserRepository {
	ret := _m.Called()

	var r0 UserRepository
	if rf, ok := ret.Get(0).(func() UserRepository); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(UserRepository)
		}
	}

	return r0
}
