name: github-actions
on:
  push:
    branches:
      - "**"
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3.0.0
        with:
          go-version: "^1.17"
      - run: go test -cover ./...
